save_dir: /hdd8/wenqiao/covidx/save
save_name: fixmatch_covidx
resume: False
load_path: None
overwrite: True
epoch: 1
num_train_iter: 100000
num_eval_iter: 5000
num_labels: 1000
batch_size: 16
eval_batch_size: 1024
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: /hdd8/wenqiao/covidx/binary
dataset: covidx
train_sampler: RandomSampler
num_classes: 2
num_workers: 1
alg: fixmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10005
dist_backend: nccl
gpu: 2
