save_dir: /hdd8/wenqiao/spinemet/ssl-al/save
save_name: ssl_al
resume: False
load_path: None
overwrite: True
epoch: 1
num_train_iter: 100000
num_eval_iter: 10000
num_labels: 12800
batch_size: 64
eval_batch_size: 100
hard_label: True
T: 0.5
p_cutoff: 0.7
ulb_loss_ratio: 10
uratio: 5
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0003
amp: False
net: ResNet50
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: /hdd8/wenqiao/spinemet/dataset/binary
dataset: imagenet
train_sampler: RandomSampler
num_classes: 1000
num_workers: 1
alg: fixmatch
seed: 1
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10004
dist_backend: nccl
gpu: None
